"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.save = void 0;
var fs_1 = __importDefault(require("fs"));
var path_1 = __importDefault(require("path"));
var fileName = "Tailwind.elm";
var generate = function (classes) {
    var elmify = function (_a) {
        var className = _a.className, name = _a.name;
        return "\n\n" + name + " : Tailwind\n" + name + " =\n    Tailwind \"" + className + "\"\n";
    };
    return "module Tailwind exposing (Tailwind, tailwind, unwrap, " + classes
        .map(function (cl) { return cl.name; })
        .join(", ") + ")\n\n-- Generated by tailwind-generator, be careful when editing this file\n\nimport Html\nimport Html.Attributes as Attributes\nimport List\n\n\ntype Tailwind\n    = Tailwind String\n\n\nunwrap : List Tailwind -> String\nunwrap cs =\n    cs |> List.map (\\(Tailwind c) -> c) |> String.join \" \"\n\ntailwind : List Tailwind -> Html.Attribute msg\ntailwind cs =\n    Attributes.class <| unwrap cs\n" + classes.map(elmify).join("") + "\n  ";
};
exports.save = function (dir, classes) {
    fs_1.default.writeFileSync(path_1.default.join(dir, fileName), generate(classes));
};
