"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var fs_1 = __importDefault(require("fs"));
var path_1 = __importDefault(require("path"));
var fileName = "Tailwind.re";
var interfaceFileName = "Tailwind.rei";
var generate = function (classes) {
    var reasonalize = function (_a) {
        var className = _a.className, name = _a.name;
        return "\nlet " + name + " = Tailwind(\"" + className + "\");\n";
    };
    return "// Generated by tailwind-generator, be careful when editing this file\n\ntype tailwind\n  = Tailwind(string)\n\nlet tailwind = classes =>\n  classes->Belt.List.map((Tailwind(c)) => c)->Belt.List.toArray\n  |> Js.Array.joinWith(\" \");\n\nlet tailwindOpt = classes =>\n  classes->Js.List.filterMap((. x) => x, _)->tailwind;\n" + classes.map(reasonalize).join("") + "\n  ";
};
var generateInterface = function (classes) {
    var reasonalize = function (_a) {
        var name = _a.name;
        return "\nlet " + name + " : tailwind;\n";
    };
    return "// Generated by tailwind-generator, be careful when editing this file\n\ntype tailwind;\n\nlet tailwind : list(tailwind) => string;\n\nlet tailwindOpt : list(option(tailwind)) => string;\n" + classes.map(reasonalize).join("") + "\n  ";
};
exports.save = function (dir, classes) {
    fs_1.default.writeFileSync(path_1.default.join(dir, fileName), generate(classes));
    fs_1.default.writeFileSync(path_1.default.join(dir, interfaceFileName), generateInterface(classes));
};
