import fs from "fs";
import path from "path";

import { Adapter, Class } from "../types";

const fileName = "Classes.elm";

const generate = (classes: Class[]): string => {
  const elmify = ({ className, name }: Class): string => `

${name} : TailwindClass
${name} =
    TailwindClass "${className}"
`;

  return `module Tailwind.Classes exposing (TailwindClass, tailwind, unwrap, ${classes
    .map(cl => cl.name)
    .join(", ")})

-- Generated by tailwind-generator, be careful when editing this file

import Html
import Html.Attributes as Attributes
import List


type TailwindClass
    = TailwindClass String


unwrap : List TailwindClass -> String
unwrap cs =
    cs |> List.map (\\(TailwindClass c) -> c) |> String.join " "

tailwind : List TailwindClass -> Html.Attribute msg
tailwind cs =
    Attributes.class <| unwrap cs
${classes.map(elmify).join("")}
  `;
};

export const save: Adapter["save"] = (dir, classes) => {
  fs.writeFileSync(path.join(dir, fileName), generate(classes));
};
